import { defineConfig } from 'pollen-css/utils';

export default defineConfig((pollen) => ({
  output: './theme/pollen.css',
  modules: {
    color: {
      white: '#ffffff',
      black: '#000000',
      gray: '#eee',
      'info-lighter': '#dbe9fe',
      'info-light': '#93c3fd',
      'info-default': '#3b7ef6',
      'info-dark': '#1d4ad8',
      'info-darker': '#1e388a',
      'succes-lighter': '#dcfce6',
      'succes-light': '#86efaa',
      'succes-default': '#22c55b',
      'succes-dark': '#15803b',
      'succes-darker': '#14532c',
      'warning-lighter': '#fcfec3',
      'warning-light': '#fdf547',
      'warning-default': '#eace08',
      'warning-dark': '#a17407',
      'warning-darker': '#714a12',
      'danger-lighter': '#fee2e2',
      'danger-light': '#fca5a5',
      'danger-default': '#ef4444',
      'danger-dark': '#b91c1c',
      'danger-darker': '#7f1d1d',
    },
    //  Typography
    font: false,
    weight: false,
    line: false,
    letter: false,
    prose: false,
    //  Layout
    scale: false,
    "scale-fluid":false,
    size: false,
    ratio: false,
    width: {
      xs: '480px',
      sm: '720px',
      md: '1024px',
      lg: '1280px',
      xl: '1440px',
      '2k': '2160px',
      min: 'min-content',
      max: 'max-content',
      full: '100%',
      screen: '100vw',
    },
    radius: {
      px: '1px',
      xs: '2px',
      sm: '4px',
      md: '8px',
      default: '16px',
      lg: '32px',
      xl: '64px',
      full: '9999px',
    },
    //  UI
    ease: false,
    layer: false,
  },
}));
