### Variables
@host=localhost
@port=8000
@path=/api/products
@baseUrl = http://{{host}}:{{port}}{{path}}
@id=66b4ba3305211655c07ae3b8


### Create a new product
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "name": "Sample Product",
  "description": "This is a sample product description.",
  "price": 99.99,
  "category":"Cookie",
  "discountPercentage":0,
  "rating":0,
  "stock":0,
  "availabilityStatus":"Out of Stock",
  "thumbnail":"https://via.placeholder.com/150",
  "images":[],
  "reviews":[]
}

### Get all products
GET {{baseUrl}}?page=1&pageSize=10 HTTP/1.1

### Get a single product by ID
GET {{baseUrl}}/{{id}} HTTP/1.1

### Update a product by ID
PUT {{baseUrl}}/{{id}} HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "name": "Updated Product",
  "description": "This is an updated product description.",
  "image": "https://example.com/images/updated-product.jpg",
  "price": 129,
  "category":"Cookie",
  "discountPercentage":0,
  "rating":0,
  "stock":0,
  "availabilityStatus":"Out of Stock",
  "thumbnail":"https://via.placeholder.com/150",
  "images":[],
  "reviews":[]
}

### Delete a product by ID
DELETE {{baseUrl}}/{{id}} HTTP/1.1
