### Variables
@host=localhost
@port=8080
@path=/api/products
@baseUrl = http://{{host}}:{{port}}{{path}}
@id=66b4ba3305211655c07ae3b8


### Create a new product
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "name": "Summer box (Limoncello)",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper mi sed nisi ornare, nec ullamcorper nunc vehicula. Donec ut justo quis erat volutpat congue id eu erat. Integer ac sodales purus. Nullam congue tellus.",
  "price": 19.99,
  "category":"Gift",
  "discountPercentage":0,
  "stock":4,
  "availabilityStatus":"Out of Stock",
  "thumbnail":"https://sweetgirlCookies.com/wp-content/uploads/2021/01/SGC-Prod_6Big_12Classic.png",
  "images":[],
  "reviews":[{
        "rating": 5,
        "comment": "This is a great product!",
        "date": "2021-09-01T00:00:00Z",
        "reviewerName": "John Doe",
        "reviewerEmail": "JohnDoe@test.be"
    },
    {
        "rating": 2,
        "comment": "Very unhappy with my purchase!",
        "date": "2021-09-01T00:00:00Z",
        "reviewerName": "Dirk Pore",
        "reviewerEmail": "DP@test.be"
    }
    ]
}

### Get all products
GET {{baseUrl}} HTTP/1.1

### Get a single product by ID
GET {{baseUrl}}/{{id}} HTTP/1.1

### Update a product by ID
PUT {{baseUrl}}/{{id}} HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "name": "Updated Product",
  "description": "This is an updated product description.",
  "image": "https://example.com/images/updated-product.jpg",
  "price": 129,
  "category":"Cookie",
  "discountPercentage":0,
  "rating":0,
  "stock":0,
  "availabilityStatus":"Out of Stock",
  "thumbnail":"https://via.placeholder.com/150",
  "images":[],
  "reviews":[]
}

### Delete a product by ID
DELETE {{baseUrl}}/{{id}} HTTP/1.1
